version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_container_db
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: luis
      POSTGRES_PASSWORD: meraki
    ports:
      - 5432:5432
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: luissolivaresp@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
